### ISSUE TITLE
Release the codes

### ISSUE THREAD

**Issue by zhenyuZ-HUST** [chenghao-ch94/FGFL#1]
Hello authors,

Any chance that you would like to release the codes?

**Comment by chenghao-ch94** [comment]
Thank you for your interest in our work. I am now checking some pretrained models and I need some time to organize the code. I will try to release the code asap.

From: zhenyuZ-HUST ***@***.***>
Sent: Wednesday, May 22, 2024 11:09 AM
To: chenghao-ch94/FGFL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chenghao-ch94/FGFL] Release the codes (Issue #1)


Hello authors,

Any chance that you would like to release the codes?

**Comment by mobulan** [comment]
+1

**Comment by LiuXiYing** [comment]
+1

**Comment by donglongzi** [comment]
me too

**Comment by Sandy-program** [comment]
Looking forward to your code
